### ISSUE TITLE
Kanban Setup

### ISSUE THREAD

**Issue by Mwapsam** [clintonjosephs/recipe-app#13]
In this task, we initialized the new project and set up the Kanban board

[Kanban board](https://github.com/clintonjosephs/recipe-app/projects/1
)

Team size - 2 members
- Team member 1 @Mwapsam 
- Team member 2 @clintonjosephs

**Comment by dasileker** [comment]
### **Hi @clintonjosephs,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
